#!/bin/bash

set -e

version=`git describe --tags`
echo $version

here=$(dirname "$0")
cd $here/../dist

sftp -oBatchMode=no -b - thomasv@download.electrumfair.org << !
   cd electrumfair-downloads
   mkdir $version
   cd $version
   mput *
   bye
!
